version: 0.2

phases:
    
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 755537473478.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_REPO_NAME=755537473478.dkr.ecr.us-east-1.amazonaws.com/amazonrepo
      - IMAGE_TAG=v1
      - aws eks --region us-east-1 update-kubeconfig --name kentitilayo2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
 

      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Push the latest image to cluster
      - kubectl apply -f deployment.yml
